// Enhanced SBA Verification Data with Inquiries
// Generated: 2025-08-29T17:33:34.403951

const sbaVerificationData = [
  {
    "id": 29379,
    "name": "SBA Pre-Qualified: 12-Year-Old SaaS Business | Owner Works 5 Hours per Week",
    "status": "sold",
    "closed_at": "2025-03-18 06:27:07",
    "closed_commission": 263916.0,
    "total_inquiries": 1687,
    "total_lois": 4,
    "sba_lois": 4,
    "has_sba_loi": true,
    "winning_loi_sba": true,
    "financing_type": "SBA",
    "pct_sba_lois": 100.0,
    "days_on_market": 513,
    "days_under_loi": 116,
    "days_to_loi": 141
  },
  {
    "id": 30193,
    "name": "SBA Email SaaS Company | Low 1 Customer per Month Churn | Sales Experience Needed",
    "status": "sold",
    "closed_at": "2024-08-06 23:59:02",
    "closed_commission": 60000.0,
    "total_inquiries": 1076,
    "total_lois": 14,
    "sba_lois": 1,
    "has_sba_loi": true,
    "winning_loi_sba": false,
    "financing_type": "Non-SBA",
    "pct_sba_lois": 7.142857142857142,
    "days_on_market": 217,
    "days_under_loi": null,
    "days_to_loi": 212
  },
  {
    "id": 22437,
    "name": "SBA Pre-Qual | 8 Yr Old Reputable SaaS Portfolio, High Barrier to Entry, Passive,  2.3M+ Users",
    "status": "sold",
    "closed_at": "2023-09-13 15:51:38",
    "closed_commission": 322578.0,
    "total_inquiries": 1044,
    "total_lois": 5,
    "sba_lois": 3,
    "has_sba_loi": true,
    "winning_loi_sba": false,
    "financing_type": "Non-SBA",
    "pct_sba_lois": 60.0,
    "days_on_market": 485,
    "days_under_loi": 7,
    "days_to_loi": 435
  },
  {
    "id": 20684,
    "name": "SBA Pre-Qualified | Education Vertical Subscription | SaaS and Subscription Business",
    "status": "sold",
    "closed_at": "2023-02-14 19:04:02",
    "closed_commission": 75000.0,
    "total_inquiries": 911,
    "total_lois": 1,
    "sba_lois": 0,
    "has_sba_loi": false,
    "winning_loi_sba": false,
    "financing_type": "Non-SBA",
    "pct_sba_lois": 0.0,
    "days_on_market": 197,
    "days_under_loi": 71,
    "days_to_loi": 126
  },
  {
    "id": 26636,
    "name": "SBA Camper Van Ecom Brand | 70% Organic Traffic | $900+ AOV | 8-Figure Revenue Potential",
    "status": "sold",
    "closed_at": "2025-01-09 00:40:02",
    "closed_commission": 235264.0,
    "total_inquiries": 835,
    "total_lois": 33,
    "sba_lois": 23,
    "has_sba_loi": true,
    "winning_loi_sba": true,
    "financing_type": "SBA",
    "pct_sba_lois": 69.6969696969697,
    "days_on_market": 364,
    "days_under_loi": 0,
    "days_to_loi": 232
  },
  {
    "id": 23592,
    "name": "SBA Prequalified: Leading Personal Finance Content Business w/Diversified Earnings",
    "status": "sold",
    "closed_at": "2023-04-08 04:13:02",
    "closed_commission": 287500.0,
    "total_inquiries": 750,
    "total_lois": 4,
    "sba_lois": 0,
    "has_sba_loi": false,
    "winning_loi_sba": false,
    "financing_type": "Non-SBA",
    "pct_sba_lois": 0.0,
    "days_on_market": 272,
    "days_under_loi": 85,
    "days_to_loi": 169
  },
  {
    "id": 29530,
    "name": "Alternascript & Hair Labs",
    "status": "sold",
    "closed_at": "2025-01-10 21:16:35",
    "closed_commission": 40000.0,
    "total_inquiries": 628,
    "total_lois": 3,
    "sba_lois": 0,
    "has_sba_loi": false,
    "winning_loi_sba": false,
    "financing_type": "Non-SBA",
    "pct_sba_lois": 0.0,
    "days_on_market": 457,
    "days_under_loi": 16,
    "days_to_loi": 7
  },
  {
    "id": 33589,
    "name": "7 Year Old Amazon FBA Business Selling Lawn Tools w/37% Net Margins & Steady 3 Year Growth",
    "status": "sold",
    "closed_at": "2025-02-26 23:09:41",
    "closed_commission": 175108.0,
    "total_inquiries": 607,
    "total_lois": 2,
    "sba_lois": 1,
    "has_sba_loi": true,
    "winning_loi_sba": false,
    "financing_type": "Non-SBA",
    "pct_sba_lois": 50.0,
    "days_on_market": 177,
    "days_under_loi": 28,
    "days_to_loi": 37
  },
  {
    "id": 30199,
    "name": "SBA Pre-Qualified | 14 Year-Old Eyewear Brands | Exclusive Vendors | B2B Growth Opportunities",
    "status": "sold",
    "closed_at": "2025-02-28 22:31:02",
    "closed_commission": 78750.0,
    "total_inquiries": 603,
    "total_lois": 39,
    "sba_lois": 19,
    "has_sba_loi": true,
    "winning_loi_sba": false,
    "financing_type": "Non-SBA",
    "pct_sba_lois": 48.717948717948715,
    "days_on_market": 86,
    "days_under_loi": 67,
    "days_to_loi": null
  },
  {
    "id": 25215,
    "name": "SBA Prequalified: 21+ Year Old Transportation Industry Ecom Business With No Paid Ads",
    "status": "sold",
    "closed_at": "2023-04-11 19:40:02",
    "closed_commission": 381400.0,
    "total_inquiries": 583,
    "total_lois": 1,
    "sba_lois": 1,
    "has_sba_loi": true,
    "winning_loi_sba": true,
    "financing_type": "SBA",
    "pct_sba_lois": 100.0,
    "days_on_market": 162,
    "days_under_loi": 74,
    "days_to_loi": 88
  },
  {
    "id": 13990,
    "name": "SBA Prequalified | 7 Year-Old Blue-Collar Workwear Brand w/38% Net Margins | Growth Opportunities",
    "status": "sold",
    "closed_at": "2024-09-30 22:39:09",
    "closed_commission": 305000.0,
    "total_inquiries": 574,
    "total_lois": 3,
    "sba_lois": 1,
    "has_sba_loi": true,
    "winning_loi_sba": true,
    "financing_type": "SBA",
    "pct_sba_lois": 33.33333333333333,
    "days_on_market": 218,
    "days_under_loi": 102,
    "days_to_loi": 15
  },
  {
    "id": 27936,
    "name": "SBA Qualified Growing Real Estate Digital Services Business | 50% Net Margins | $500+ LTV",
    "status": "sold",
    "closed_at": "2023-10-14 18:37:02",
    "closed_commission": 104050.0,
    "total_inquiries": 570,
    "total_lois": 7,
    "sba_lois": 1,
    "has_sba_loi": true,
    "winning_loi_sba": false,
    "financing_type": "Non-SBA",
    "pct_sba_lois": 14.285714285714285,
    "days_on_market": 116,
    "days_under_loi": 12,
    "days_to_loi": 94
  },
  {
    "id": 26353,
    "name": "SBA Pre-qualified 20-Year-Old Library Resource Business | 77 Year-Old Owner Retiring",
    "status": "sold",
    "closed_at": "2023-08-26 03:25:02",
    "closed_commission": 35000.0,
    "total_inquiries": 545,
    "total_lois": 7,
    "sba_lois": 0,
    "has_sba_loi": false,
    "winning_loi_sba": false,
    "financing_type": "Non-SBA",
    "pct_sba_lois": 0.0,
    "days_on_market": 114,
    "days_under_loi": 39,
    "days_to_loi": 14
  },
  {
    "id": 19224,
    "name": "SBA Pre-Qualified 19-Year-Old Automotive Parts Brand | Diversified Revenue | 5% YoY SDE Growth",
    "status": "sold",
    "closed_at": "2024-09-27 14:58:02",
    "closed_commission": 215000.0,
    "total_inquiries": 543,
    "total_lois": 2,
    "sba_lois": 0,
    "has_sba_loi": false,
    "winning_loi_sba": false,
    "financing_type": "Non-SBA",
    "pct_sba_lois": 0.0,
    "days_on_market": 171,
    "days_under_loi": 143,
    "days_to_loi": 28
  },
  {
    "id": 23620,
    "name": "SBA Pre-Qualified Custom Artwork Shopify Business | 75% Digital Sales | Turnkey Operations",
    "status": "sold",
    "closed_at": "2025-05-31 18:30:06",
    "closed_commission": 99000.0,
    "total_inquiries": 522,
    "total_lois": 15,
    "sba_lois": 9,
    "has_sba_loi": true,
    "winning_loi_sba": true,
    "financing_type": "SBA",
    "pct_sba_lois": 60.0,
    "days_on_market": 276,
    "days_under_loi": null,
    "days_to_loi": 64
  },
  {
    "id": 18124,
    "name": "SBA Pre-Qualified E-Com Biz | $1m+ Rev on $0 Ad Spend | Opps to Modernize 25 Year Old Biz",
    "status": "sold",
    "closed_at": "2022-07-18 07:56:25",
    "closed_commission": null,
    "total_inquiries": 519,
    "total_lois": 0,
    "sba_lois": 0,
    "has_sba_loi": false,
    "winning_loi_sba": false,
    "financing_type": "Non-SBA",
    "pct_sba_lois": 0.0,
    "days_on_market": 441,
    "days_under_loi": null,
    "days_to_loi": null
  },
  {
    "id": 19170,
    "name": "SBA Pre Qualified - 8-Year-Old Women\u2019s Boutique - $670K SDE w/ Only $55k Ad Spend",
    "status": "sold",
    "closed_at": "2022-09-07 00:50:02",
    "closed_commission": null,
    "total_inquiries": 489,
    "total_lois": 0,
    "sba_lois": 0,
    "has_sba_loi": false,
    "winning_loi_sba": false,
    "financing_type": "Non-SBA",
    "pct_sba_lois": 0.0,
    "days_on_market": 237,
    "days_under_loi": null,
    "days_to_loi": null
  },
  {
    "id": 28179,
    "name": "SBA PQ | Passive Test Prep Business | YouTube 75.6K Subs - 9.5M Views | YoY Rev/SDE Growth 63% & 67%",
    "status": "sold",
    "closed_at": "2025-04-03 18:52:34",
    "closed_commission": 50000.0,
    "total_inquiries": 465,
    "total_lois": 19,
    "sba_lois": 10,
    "has_sba_loi": true,
    "winning_loi_sba": true,
    "financing_type": "SBA",
    "pct_sba_lois": 52.63157894736842,
    "days_on_market": 59,
    "days_under_loi": 51,
    "days_to_loi": null
  },
  {
    "id": 21049,
    "name": "SBA Pre Qualified: 4,000+ Course Membership Business With 83% Recurring Revenue 155% YoY SDE Growth",
    "status": "sold",
    "closed_at": "2024-02-23 06:49:10",
    "closed_commission": 275000.0,
    "total_inquiries": 455,
    "total_lois": 5,
    "sba_lois": 4,
    "has_sba_loi": true,
    "winning_loi_sba": true,
    "financing_type": "SBA",
    "pct_sba_lois": 80.0,
    "days_on_market": 173,
    "days_under_loi": 150,
    "days_to_loi": 9
  },
  {
    "id": 28025,
    "name": "Partial SBA Pre-Qualified Test Prep Membership Business | 100% Organic | Zero Marketing | 15K Subs",
    "status": "sold",
    "closed_at": "2024-10-02 01:59:21",
    "closed_commission": 297650.0,
    "total_inquiries": 451,
    "total_lois": 1,
    "sba_lois": 0,
    "has_sba_loi": false,
    "winning_loi_sba": false,
    "financing_type": "Non-SBA",
    "pct_sba_lois": 0.0,
    "days_on_market": 463,
    "days_under_loi": 106,
    "days_to_loi": 357
  },
  {
    "id": 24362,
    "name": "SBA Pre-Qualified | 11-Yr-Old Amazon FBA | Eyewear | 37,000 4.4-Star Reviews | Positive YOY Trends",
    "status": "sold",
    "closed_at": "2024-04-29 21:28:32",
    "closed_commission": 273444.0,
    "total_inquiries": 441,
    "total_lois": 2,
    "sba_lois": 1,
    "has_sba_loi": true,
    "winning_loi_sba": true,
    "financing_type": "SBA",
    "pct_sba_lois": 50.0,
    "days_on_market": 323,
    "days_under_loi": 95,
    "days_to_loi": 126
  },
  {
    "id": 23097,
    "name": "13-Year-Old Specialty Hand Tools Business | 47% YOY SDE Growth | 40% Repeat Rev on Branded Site",
    "status": "sold",
    "closed_at": "2024-06-20 20:46:51",
    "closed_commission": 464250.0,
    "total_inquiries": 438,
    "total_lois": 3,
    "sba_lois": 0,
    "has_sba_loi": false,
    "winning_loi_sba": false,
    "financing_type": "Non-SBA",
    "pct_sba_lois": 0.0,
    "days_on_market": 298,
    "days_under_loi": 136,
    "days_to_loi": 158
  },
  {
    "id": 19845,
    "name": "SBA Pre-Qualified: B2B SaaS w/ 17.8% Earnings Growth and 12 Yr History",
    "status": "sold",
    "closed_at": "2022-11-08 15:21:01",
    "closed_commission": null,
    "total_inquiries": 405,
    "total_lois": 0,
    "sba_lois": 0,
    "has_sba_loi": false,
    "winning_loi_sba": false,
    "financing_type": "Non-SBA",
    "pct_sba_lois": 0.0,
    "days_on_market": 127,
    "days_under_loi": null,
    "days_to_loi": null
  },
  {
    "id": 17818,
    "name": "SBA Pre-Qualified SAAS Business | 95% Client Retention | Growing 69% YOY | Amazing Growth Potential",
    "status": "sold",
    "closed_at": "2022-07-18 07:56:25",
    "closed_commission": null,
    "total_inquiries": 388,
    "total_lois": 0,
    "sba_lois": 0,
    "has_sba_loi": false,
    "winning_loi_sba": false,
    "financing_type": "Non-SBA",
    "pct_sba_lois": 0.0,
    "days_on_market": 460,
    "days_under_loi": null,
    "days_to_loi": null
  },
  {
    "id": 26838,
    "name": "SBA Shopify Custom Home Decor | $130 AOV | High Gross Margins | US Manufacturing",
    "status": "sold",
    "closed_at": "2024-12-14 23:02:02",
    "closed_commission": 82500.0,
    "total_inquiries": 360,
    "total_lois": 11,
    "sba_lois": 6,
    "has_sba_loi": true,
    "winning_loi_sba": true,
    "financing_type": "SBA",
    "pct_sba_lois": 54.54545454545454,
    "days_on_market": 72,
    "days_under_loi": null,
    "days_to_loi": 50
  },
  {
    "id": 32811,
    "name": "5-Year-Old SaaS Business | WordPress and Shopify | Low Owner Workload",
    "status": "sold",
    "closed_at": "2025-01-07 23:07:18",
    "closed_commission": 210160.0,
    "total_inquiries": 360,
    "total_lois": 3,
    "sba_lois": 3,
    "has_sba_loi": true,
    "winning_loi_sba": true,
    "financing_type": "SBA",
    "pct_sba_lois": 100.0,
    "days_on_market": 191,
    "days_under_loi": 152,
    "days_to_loi": 38
  },
  {
    "id": 26302,
    "name": "SBA Qualified Growing Baby Products Brand | Amazon FBA and Shopify | Established Team | US Supplier",
    "status": "sold",
    "closed_at": "2023-12-10 01:43:02",
    "closed_commission": 48000.0,
    "total_inquiries": 352,
    "total_lois": 1,
    "sba_lois": 1,
    "has_sba_loi": true,
    "winning_loi_sba": true,
    "financing_type": "SBA",
    "pct_sba_lois": 100.0,
    "days_on_market": 105,
    "days_under_loi": 107,
    "days_to_loi": null
  },
  {
    "id": 23675,
    "name": "SBA Pre-qual 22 year old Snow Sports Biz | $2.18m Rev | 1.2% Ad Spend | Huge Growth Opportunities",
    "status": "sold",
    "closed_at": "2023-01-20 17:53:02",
    "closed_commission": 160000.0,
    "total_inquiries": 345,
    "total_lois": 1,
    "sba_lois": 1,
    "has_sba_loi": true,
    "winning_loi_sba": true,
    "financing_type": "SBA",
    "pct_sba_lois": 100.0,
    "days_on_market": 121,
    "days_under_loi": 71,
    "days_to_loi": 50
  },
  {
    "id": 29598,
    "name": "SBA Pre-Qualified Health & Wellness Content Sites | 58% SDE Margins | Strong Backlinks",
    "status": "sold",
    "closed_at": "2024-03-11 19:45:15",
    "closed_commission": 145600.0,
    "total_inquiries": 332,
    "total_lois": 7,
    "sba_lois": 4,
    "has_sba_loi": true,
    "winning_loi_sba": true,
    "financing_type": "SBA",
    "pct_sba_lois": 57.14285714285714,
    "days_on_market": 124,
    "days_under_loi": 59,
    "days_to_loi": 7
  },
  {
    "id": 27689,
    "name": "SBA Qualified Yoga Digital Products | Operator in Place | 8 Years Old | Marketing Needed",
    "status": "sold",
    "closed_at": "2023-10-14 17:48:02",
    "closed_commission": 63750.0,
    "total_inquiries": 320,
    "total_lois": 1,
    "sba_lois": 1,
    "has_sba_loi": true,
    "winning_loi_sba": true,
    "financing_type": "SBA",
    "pct_sba_lois": 100.0,
    "days_on_market": 144,
    "days_under_loi": 103,
    "days_to_loi": 41
  },
  {
    "id": 18107,
    "name": "SBA Pre-Qualified Virtual Team Building Business | $526k of SDE on $660k in Revenue | 2.1x Multiple",
    "status": "sold",
    "closed_at": "2022-07-18 07:56:25",
    "closed_commission": null,
    "total_inquiries": 304,
    "total_lois": 0,
    "sba_lois": 0,
    "has_sba_loi": false,
    "winning_loi_sba": false,
    "financing_type": "Non-SBA",
    "pct_sba_lois": 0.0,
    "days_on_market": 426,
    "days_under_loi": null,
    "days_to_loi": null
  },
  {
    "id": 17700,
    "name": "SBA-Eligible: Leading Amazon FBA Outdoor & Survival Brand w/ Triple Digit Growth",
    "status": "sold",
    "closed_at": "2022-07-18 07:56:25",
    "closed_commission": null,
    "total_inquiries": 300,
    "total_lois": 0,
    "sba_lois": 0,
    "has_sba_loi": false,
    "winning_loi_sba": false,
    "financing_type": "Non-SBA",
    "pct_sba_lois": 0.0,
    "days_on_market": 558,
    "days_under_loi": null,
    "days_to_loi": null
  },
  {
    "id": 26074,
    "name": "SBA Pre-Qual | Proprietary Saas Tools for Traders, 1700 Customers, Built-in Growth, 4.8 Star Rating",
    "status": "sold",
    "closed_at": "2025-06-03 20:17:28",
    "closed_commission": 397000.0,
    "total_inquiries": 283,
    "total_lois": 4,
    "sba_lois": 3,
    "has_sba_loi": true,
    "winning_loi_sba": true,
    "financing_type": "SBA",
    "pct_sba_lois": 75.0,
    "days_on_market": 288,
    "days_under_loi": 103,
    "days_to_loi": 101
  },
  {
    "id": 27495,
    "name": "Virtual Summit Business in the Education Space | 58% Net Margins | Multiple Growth Opps",
    "status": "sold",
    "closed_at": "2023-12-19 23:07:03",
    "closed_commission": 100000.0,
    "total_inquiries": 279,
    "total_lois": 4,
    "sba_lois": 0,
    "has_sba_loi": false,
    "winning_loi_sba": false,
    "financing_type": "Non-SBA",
    "pct_sba_lois": 0.0,
    "days_on_market": 209,
    "days_under_loi": 60,
    "days_to_loi": 49
  },
  {
    "id": 21790,
    "name": "14 Yr-Old Financial Investment Tracking SaaS Business, Consistent Growth, Strong Recurring Revenue",
    "status": "sold",
    "closed_at": "2022-07-18 07:56:25",
    "closed_commission": null,
    "total_inquiries": 278,
    "total_lois": 0,
    "sba_lois": 0,
    "has_sba_loi": false,
    "winning_loi_sba": false,
    "financing_type": "Non-SBA",
    "pct_sba_lois": 0.0,
    "days_on_market": 145,
    "days_under_loi": null,
    "days_to_loi": null
  }
];

const sbaVerificationStats = {
  "sba": {
    "count": 15,
    "median_inquiries": 441,
    "mean_inquiries": 527.6,
    "median_days_on_market": 173,
    "mean_days_on_market": 208.86666666666667,
    "median_days_under_loi": 102,
    "median_days_to_loi": 50,
    "median_commission": 210160.0,
    "total_commission": 2990034.0
  },
  "non_sba": {
    "count": 20,
    "median_inquiries": 531,
    "mean_inquiries": 556.4,
    "median_days_on_market": 227,
    "mean_days_on_market": 282.8,
    "median_days_under_loi": 63,
    "median_days_to_loi": 110,
    "median_commission": 104050.0,
    "total_commission": 2254886.0
  }
};

// Export for use in dashboard
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { sbaVerificationData, sbaVerificationStats };
}
